repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix=lf]
    description: Forces to replace line ending by the UNIX 'lf' character.
  - id: check-yaml
  - id: check-json

# formatting and linting for terraform
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 'v1.77.1' # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
  - id: terraform_fmt
  - id: terraform_tflint
    args:
    - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
  - id: terraform_validate
  - id: terraform_checkov
  # - id: terraform_docs # applied via terraform-releaser
