repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer

# terrafrom - linting for terraform
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 'v1.77.1'
  hooks:
  - id: terraform_fmt
  - id: terraform_tflint
    args:
    - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

# terraform - static code analysis
- repo: https://github.com/bridgecrewio/checkov.git
  rev: '3.1.55'
  hooks:
  - id: checkov
    args: [
      --soft-fail,
      --quiet
    ]
