# Run terraform checks on PR

name: Check Terraform

on:
  pull_request:
    branches:
      - master
  # push:
  #   branches:
  #     - master

permissions:
  contents: read

jobs:
  terraform-validation:
    name: Terraform Validate
    runs-on: ubuntu-latest
    strategy:
      matrix: { env: [
        "gcp/bq-dataset",
        "gcp/ps-write-subscription"]}
    defaults:
      run:
        working-directory: "${{ matrix.env }}"
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color
  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    strategy:
      matrix: { env: [
        "gcp/bq-dataset",
        "gcp/ps-write-subscription"]}
    defaults:
      run:
        working-directory: "${{ matrix.env }}"
    steps:
      - name: Dummy
        run: pwd